import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
    './src/lib/**/*.{js,ts,jsx,tsx,mdx}',
    './src/styles/**/*.css',
  ],
  theme: {
    extend: {
      fontFamily: {
        // Plus Jakarta Sans (karya desainer Indonesia) untuk UI & teks isi.
        sans: ['var(--font-jakarta)', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        // Fraunces: serif bervariabel yang hangat, untuk judul besar bernuansa jurnal alam.
        display: ['var(--font-fraunces)', 'ui-serif', 'Georgia', 'serif'],
      },
      colors: {
        surface: {
          canvas: 'var(--surface-canvas)',
          base: 'var(--surface-base)',
          'brand-tint': 'var(--surface-brand-tint)',
          raised: 'var(--surface-raised)',
          subtle: 'var(--surface-subtle)',
          sunken: 'var(--surface-sunken)',
          inverse: 'var(--surface-inverse)',
          scrim: 'var(--surface-scrim)',
          forest: 'var(--surface-forest)',
          meadow: 'var(--surface-meadow)',
          sand: 'var(--surface-sand)',
          sky: 'var(--surface-sky)',
          ember: 'var(--surface-ember)',
        },
        text: {
          primary: 'var(--text-primary)',
          secondary: 'var(--text-secondary)',
          muted: 'var(--text-muted)',
          inverse: 'var(--text-inverse)',
          'inverse-muted': 'var(--text-inverse-muted)',
          'on-brand': 'var(--text-on-brand)',
          accent: 'var(--accent-text)',
          warm: 'var(--accent-warm)',
        },
        action: {
          primary: 'var(--action-primary)',
          'primary-hover': 'var(--action-primary-hover)',
          'primary-active': 'var(--action-primary-active)',
          secondary: 'var(--action-secondary)',
          'secondary-hover': 'var(--action-secondary-hover)',
          'secondary-text': 'var(--action-secondary-text)',
          accent: 'var(--action-accent)',
          'accent-hover': 'var(--action-accent-hover)',
          danger: 'var(--action-danger)',
          'danger-hover': 'var(--action-danger-hover)',
        },
        tag: {
          surface: 'var(--tag-surface)',
          text: 'var(--tag-text)',
          border: 'var(--tag-border)',
        },
        border: {
          subtle: 'var(--border-subtle)',
          strong: 'var(--border-strong)',
          brand: 'var(--border-brand)',
          inverse: 'var(--border-inverse)',
          'inverse-subtle': 'var(--border-inverse-subtle)',
          'inverse-hover': 'var(--border-inverse-hover)',
        },
        focus: {
          ring: 'var(--focus-ring)',
          inverse: 'var(--focus-ring-inverse)',
        },
        status: {
          'info-surface': 'var(--status-info-surface)',
          'info-text': 'var(--status-info-text)',
          'info-border': 'var(--status-info-border)',
          'success-surface': 'var(--status-success-surface)',
          'success-text': 'var(--status-success-text)',
          'success-border': 'var(--status-success-border)',
          'warning-surface': 'var(--status-warning-surface)',
          'warning-text': 'var(--status-warning-text)',
          'warning-border': 'var(--status-warning-border)',
          'danger-surface': 'var(--status-danger-surface)',
          'danger-text': 'var(--status-danger-text)',
          'danger-border': 'var(--status-danger-border)',
          'neutral-surface': 'var(--status-neutral-surface)',
          'neutral-text': 'var(--status-neutral-text)',
          'neutral-border': 'var(--status-neutral-border)',
        },
        brand: {
          50: 'var(--brand-50)',
          100: 'var(--brand-100)',
          200: 'var(--brand-200)',
          300: 'var(--brand-300)',
          400: 'var(--brand-400)',
          500: 'var(--brand-500)',
          600: 'var(--brand-600)',
          700: 'var(--brand-700)',
          800: 'var(--brand-800)',
          900: 'var(--brand-900)',
        },
        // Palet ilustrasi: HANYA untuk fill/stroke SVG dekoratif.
        ill: {
          sky: 'var(--ill-sky)',
          'sky-warm': 'var(--ill-sky-warm)',
          sun: 'var(--ill-sun)',
          cloud: 'var(--ill-cloud)',
          'mountain-far': 'var(--ill-mountain-far)',
          mountain: 'var(--ill-mountain)',
          'forest-far': 'var(--ill-forest-far)',
          forest: 'var(--ill-forest)',
          'forest-near': 'var(--ill-forest-near)',
          'forest-deep': 'var(--ill-forest-deep)',
          meadow: 'var(--ill-meadow)',
          'meadow-light': 'var(--ill-meadow-light)',
          ground: 'var(--ill-ground)',
          path: 'var(--ill-path)',
          tent: 'var(--ill-tent)',
          'tent-shade': 'var(--ill-tent-shade)',
          'tent-alt': 'var(--ill-tent-alt)',
          flag: 'var(--ill-flag)',
          wood: 'var(--ill-wood)',
          fire: 'var(--ill-fire)',
          'fire-core': 'var(--ill-fire-core)',
          water: 'var(--ill-water)',
        },
        neutral: {
          50: 'var(--neutral-50)',
          100: 'var(--neutral-100)',
          200: 'var(--neutral-200)',
          300: 'var(--neutral-300)',
          400: 'var(--neutral-400)',
          500: 'var(--neutral-500)',
          600: 'var(--neutral-600)',
          700: 'var(--neutral-700)',
          800: 'var(--neutral-800)',
          900: 'var(--neutral-900)',
        },
      },
      spacing: {
        'section-primary': 'var(--section-y-primary)',
        'section-secondary': 'var(--section-y-secondary)',
        // Target sentuh minimum WCAG 2.2 / standar internal (44px)
        touch: '2.75rem',
      },
      minHeight: {
        touch: '2.75rem',
      },
      minWidth: {
        touch: '2.75rem',
      },
      // Radius organik: input 10px, kartu 16px, blok fitur 24px, media hero 32px, tombol pil.
      borderRadius: {
        sm: '0.375rem',
        md: '0.5rem',
        lg: '0.625rem',
        xl: '1rem',
        '2xl': '1.5rem',
        '3xl': '2rem',
        pill: '999px',
      },
      boxShadow: {
        sm: 'var(--shadow-sm)',
        md: 'var(--shadow-md)',
        lg: 'var(--shadow-lg)',
        dialog: 'var(--shadow-dialog)',
      },
      transitionTimingFunction: {
        out: 'var(--ease-out)',
      },
      keyframes: {
        'sway': { '0%,100%': { transform: 'rotate(-1.2deg)' }, '50%': { transform: 'rotate(1.2deg)' } },
        'drift': { '0%': { transform: 'translateX(0)' }, '100%': { transform: 'translateX(-40px)' } },
        'flicker': { '0%,100%': { transform: 'scaleY(1)', opacity: '1' }, '50%': { transform: 'scaleY(0.9)', opacity: '0.85' } },
        'rise': { '0%': { opacity: '0', transform: 'translateY(16px)' }, '100%': { opacity: '1', transform: 'translateY(0)' } },
      },
      animation: {
        sway: 'sway 7s ease-in-out infinite',
        drift: 'drift 40s linear infinite alternate',
        flicker: 'flicker 1.6s ease-in-out infinite',
        rise: 'rise 0.8s var(--ease-out) both',
      },
      maxWidth: {
        prose: '65ch',
      },
      fontSize: {
        // Skala display fluid: judul besar menyesuaikan lebar layar tanpa breakpoint.
        'display-xl': ['clamp(2.5rem, 1.6rem + 4vw, 4.75rem)', { lineHeight: '1.02', letterSpacing: '-0.02em' }],
        'display-lg': ['clamp(2.1rem, 1.5rem + 2.6vw, 3.5rem)', { lineHeight: '1.06', letterSpacing: '-0.015em' }],
        'display-md': ['clamp(1.75rem, 1.35rem + 1.6vw, 2.5rem)', { lineHeight: '1.1', letterSpacing: '-0.01em' }],
      },
    },
  },
  plugins: [],
}
export default config
